name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest  # Ubuntu 최신 버전에서 실행
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # GitHub 저장소에서 코드를 클론
      
      # JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'  # JDK 17 설치

      # Gradle 빌드
      - name: Gradle Build
        working-directory: ./backend  # backend 디렉토리에서 Gradle 빌드
        run: |
          ./gradlew build  # Gradle 빌드 명령 실행

      # backend 디렉토리에서 Docker 이미지 빌드
      - name: Build Backend Docker image
        working-directory: ./backend  # backend 폴더에서 작업
        run: |
          docker build -t hongboemsun682/backend:latest .  # backend 이미지를 빌드
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Push Backend Docker image to Docker Hub
        run: |
          docker push hongboemsun682/backend:latest  # Docker Hub에 이미지 푸시
