name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Temurin JDK 배포판 사용

      # Gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        working-directory: ./backend
        run: |
          chmod +x gradlew

      # Gradle 빌드
      - name: Gradle Build
        working-directory: ./backend
        run: |
          ./gradlew build

      # Docker 이미지 빌드
      - name: Build Backend Docker image
        working-directory: ./backend
        run: |
          docker build -t hongboemsun682/backend:latest .
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Push Backend Docker image to Docker Hub
        run: |
          docker push hongboemsun682/backend:latest
